### ISSUE TITLE
the order of tags

### ISSUE THREAD

**Issue by hhliliang** [timstreeter/Omni-Bus#2]
the tags order in local bus is not the same of Omni bus could you fix ? thanks

**Comment by timstreeter** [comment]
Hi Hhhliliang,

I appreciate the interest in my library.

![image](https://github.com/timstreeter/Omni-Bus/assets/150557845/db539363-348e-4feb-bde4-b640f8e74de6)

If you mean that the list of "All Tags" at "a" are not in the same order as the tags entered into the local bus at "b", then I can't fix the issue. 
All of the tags added are stored in a "Map" which sorts the tags alphabetically, so when they are read from the Map using "List Tags By Type.vi" they then also come out sorted alphabetically.

If it is important for you that the string combo box order matches the tag order going to the local bus then you could use code like this instead:
![image](https://github.com/timstreeter/Omni-Bus/assets/150557845/e3732d40-0d74-413a-9cb3-89c294f362a3)

**Comment by hhliliang** [comment]
yes，thanks for answer my question，good tool and good job
